// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC37HCCmb4qB-cwhDKqtD1hpV33Kca5VXA',
    appId: '1:954590533639:web:8ff6eaf1f068dc4020f2a2',
    messagingSenderId: '954590533639',
    projectId: 'j2j-data-sales-test',
    authDomain: 'j2j-data-sales-test.firebaseapp.com',
    storageBucket: 'j2j-data-sales-test.firebasestorage.app',
    measurementId: 'G-QH0KKXTY6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5nbxLq05hDv_XlUFtR7ZSXjwk1mwt44',
    appId: '1:954590533639:android:d610298efc08e7ea20f2a2',
    messagingSenderId: '954590533639',
    projectId: 'j2j-data-sales-test',
    storageBucket: 'j2j-data-sales-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQRNeYZLgPwnB76oCBv0UD9sX6jb1xSU',
    appId: '1:954590533639:ios:a9b585580d864ecb20f2a2',
    messagingSenderId: '954590533639',
    projectId: 'j2j-data-sales-test',
    storageBucket: 'j2j-data-sales-test.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbQRNeYZLgPwnB76oCBv0UD9sX6jb1xSU',
    appId: '1:954590533639:ios:a9b585580d864ecb20f2a2',
    messagingSenderId: '954590533639',
    projectId: 'j2j-data-sales-test',
    storageBucket: 'j2j-data-sales-test.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC37HCCmb4qB-cwhDKqtD1hpV33Kca5VXA',
    appId: '1:954590533639:web:e8f653af8e49c67220f2a2',
    messagingSenderId: '954590533639',
    projectId: 'j2j-data-sales-test',
    authDomain: 'j2j-data-sales-test.firebaseapp.com',
    storageBucket: 'j2j-data-sales-test.firebasestorage.app',
    measurementId: 'G-NKHP03MDCG',
  );

}