// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoomJJ848eZHfV5klZ3coGybIcA43rXxo',
    appId: '1:470979057778:web:0a47d9baa0bb07f59e4aeb',
    messagingSenderId: '470979057778',
    projectId: 'j2j-sales-data',
    authDomain: 'j2j-sales-data.firebaseapp.com',
    storageBucket: 'j2j-sales-data.firebasestorage.app',
    measurementId: 'G-R9SGFNHBFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWxn3mdjH8Y9yu2b7iVRw5vIXUGsyyq8',
    appId: '1:470979057778:android:63f81fdc9d9a06fd9e4aeb',
    messagingSenderId: '470979057778',
    projectId: 'j2j-sales-data',
    storageBucket: 'j2j-sales-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-Bj8C9LZjVLXCfF95AD3bwtgJW0JphI',
    appId: '1:470979057778:ios:71c175af9095bfa19e4aeb',
    messagingSenderId: '470979057778',
    projectId: 'j2j-sales-data',
    storageBucket: 'j2j-sales-data.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh-Bj8C9LZjVLXCfF95AD3bwtgJW0JphI',
    appId: '1:470979057778:ios:71c175af9095bfa19e4aeb',
    messagingSenderId: '470979057778',
    projectId: 'j2j-sales-data',
    storageBucket: 'j2j-sales-data.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoomJJ848eZHfV5klZ3coGybIcA43rXxo',
    appId: '1:470979057778:web:605d33c09f5343059e4aeb',
    messagingSenderId: '470979057778',
    projectId: 'j2j-sales-data',
    authDomain: 'j2j-sales-data.firebaseapp.com',
    storageBucket: 'j2j-sales-data.firebasestorage.app',
    measurementId: 'G-FTYZXDDNT5',
  );
}
