// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbQInPbVvloMyBXgnBIRODjqIkY4pta4',
    appId: '1:472131203776:web:bd211127182d21393cb325',
    messagingSenderId: '472131203776',
    projectId: 'j2j-sales-data-cfb68',
    authDomain: 'j2j-sales-data-cfb68.firebaseapp.com',
    storageBucket: 'j2j-sales-data-cfb68.firebasestorage.app',
    measurementId: 'G-GERK9LK2NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJIqfwvSAZPlRnlH3ODxWrJMohKBwTLA',
    appId: '1:472131203776:android:d7c6a7b52cb177503cb325',
    messagingSenderId: '472131203776',
    projectId: 'j2j-sales-data-cfb68',
    storageBucket: 'j2j-sales-data-cfb68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBou1CtBNCnSPBY-SD9anXsV-mvDOopekg',
    appId: '1:472131203776:ios:88f2a46e23e982293cb325',
    messagingSenderId: '472131203776',
    projectId: 'j2j-sales-data-cfb68',
    storageBucket: 'j2j-sales-data-cfb68.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBou1CtBNCnSPBY-SD9anXsV-mvDOopekg',
    appId: '1:472131203776:ios:88f2a46e23e982293cb325',
    messagingSenderId: '472131203776',
    projectId: 'j2j-sales-data-cfb68',
    storageBucket: 'j2j-sales-data-cfb68.firebasestorage.app',
    iosBundleId: 'com.example.j2jSpaSales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATbQInPbVvloMyBXgnBIRODjqIkY4pta4',
    appId: '1:472131203776:web:ec011f626e23636c3cb325',
    messagingSenderId: '472131203776',
    projectId: 'j2j-sales-data-cfb68',
    authDomain: 'j2j-sales-data-cfb68.firebaseapp.com',
    storageBucket: 'j2j-sales-data-cfb68.firebasestorage.app',
    measurementId: 'G-SF45PBVB98',
  );

}